adding hero detail component
raibait-vizlib/hero-app pull request #4
Opened 2021-07-07 14:12 UTC by tuzwoj

2021-07-07 14:13 UTC, tuzwoj commented on src/app/hero-list/hero-list.component.ts
> +
In case you're wondering. Hero object coming from API does not contain it's id as a value so I have to extract it from it's url.

2021-07-08 08:42 UTC, raibait-vizlib requested changes

2021-07-08 08:42 UTC, raibait-vizlib commented on src/app/hero-list/hero-list.component.ts
> +  onHeroClick(hero: Hero){
lacks return type

2021-07-08 08:42 UTC, raibait-vizlib commented on src/app/hero.service.ts
> +import { mergeMap } from 'rxjs/operators';
unused imports

2021-07-08 08:42 UTC, raibait-vizlib commented on src/app/hero-list/hero-list.component.ts
> +  extractId(url: string){
missing return type

2021-07-08 08:42 UTC, raibait-vizlib commented on src/app/hero-detail/hero-detail.component.ts
> +        console.log(this.hero);
not needed console log

2021-07-08 08:42 UTC, raibait-vizlib commented on src/app/hero-detail/hero-detail.component.ts
> +export class HeroDetailComponent implements OnInit {
can we show some loader for a user while fetching ?

2021-07-08 08:42 UTC, raibait-vizlib commented on src/app/hero-detail/hero-detail.component.scss
> +    }
its not strict but try to use more classes , maybe its a good time to start using bem ?

2021-07-08 10:23 UTC, closed without merging