Hero detail
raibait-vizlib/hero-app pull request #5
Opened 2021-07-08 10:26 UTC by tuzwoj

Some fixes from last code review + added loader in hero detail.
I will dive into BEM and refactoring CSS later, now I'd like to focus on resolving issue with fetching data to hero detail component.

2021-07-09 12:12 UTC, tuzwoj commented
ok now it's like almost finished

2021-07-12 10:40 UTC, raibait-vizlib requested changes

2021-07-12 10:40 UTC, raibait-vizlib commented on src/app/hero.service.ts
> +    return this.http.get<any>(heroUrl).pipe(
any type

2021-07-12 10:40 UTC, raibait-vizlib commented on src/app/loader/loader.component.ts
> +}
not needed oninit and constructor

2021-07-12 12:02 UTC, raibait-vizlib approved these changes

2021-07-12 12:05 UTC, merged